services:
  zitadel:
    container_name: zitadel
    restart: always
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: ['start-from-init', '--masterkeyFromEnv', '--tlsMode', 'external']
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=${ZITADEL_DATABASE_POSTGRES_HOST}'
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=${ZITADEL_DATABASE_POSTGRES_DATABASE}'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${ZITADEL_DATABASE_POSTGRES_USER_USERNAME}'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${ZITADEL_DATABASE_POSTGRES_USER_PASSWORD}'
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME}'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}'
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - 'ZITADEL_EXTERNALDOMAIN=${ZITADEL_EXTERNALDOMAIN}'
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_TLS_ENABLED=false
      - 'ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}'
      - ZITADEL_FIRSTINSTANCE_ORG_NAME=GadgetBot
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=admin
      - 'ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=${ZITADEL_ADMIN_PASSWORD}'
    expose:
      - "8080"
    depends_on:
      zitadel-db:
        condition: service_healthy
    networks:
      - zitadel
      - coolify
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5

  zitadel-db:
    container_name: zitadel-db
    restart: always
    image: postgres:17-alpine
    environment:
      - 'POSTGRES_USER=${ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME}'
      - 'POSTGRES_PASSWORD=${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}'
      - 'POSTGRES_DB=${ZITADEL_DATABASE_POSTGRES_DATABASE}'
    networks:
      - zitadel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - zitadel-data:/var/lib/postgresql/data

networks:
  zitadel:
  coolify:
    external: true

volumes:
  zitadel-data:
