/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminProductsGadgetbotsNewRouteImport } from './routes/admin/products/gadgetbots/new'
import { Route as AdminProductsGadgetbotsIdIndexRouteImport } from './routes/admin/products/gadgetbots/$id/index'
import { Route as AdminProductsGadgetbotsIdEditRouteImport } from './routes/admin/products/gadgetbots/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsGadgetbotsNewRoute =
  AdminProductsGadgetbotsNewRouteImport.update({
    id: '/products/gadgetbots/new',
    path: '/products/gadgetbots/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsGadgetbotsIdIndexRoute =
  AdminProductsGadgetbotsIdIndexRouteImport.update({
    id: '/products/gadgetbots/$id/',
    path: '/products/gadgetbots/$id/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsGadgetbotsIdEditRoute =
  AdminProductsGadgetbotsIdEditRouteImport.update({
    id: '/products/gadgetbots/$id/edit',
    path: '/products/gadgetbots/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/gadgetbots/new': typeof AdminProductsGadgetbotsNewRoute
  '/admin/products/gadgetbots/$id/edit': typeof AdminProductsGadgetbotsIdEditRoute
  '/admin/products/gadgetbots/$id': typeof AdminProductsGadgetbotsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/products/gadgetbots/new': typeof AdminProductsGadgetbotsNewRoute
  '/admin/products/gadgetbots/$id/edit': typeof AdminProductsGadgetbotsIdEditRoute
  '/admin/products/gadgetbots/$id': typeof AdminProductsGadgetbotsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/products/gadgetbots/new': typeof AdminProductsGadgetbotsNewRoute
  '/admin/products/gadgetbots/$id/edit': typeof AdminProductsGadgetbotsIdEditRoute
  '/admin/products/gadgetbots/$id/': typeof AdminProductsGadgetbotsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/products'
    | '/admin/products/gadgetbots/new'
    | '/admin/products/gadgetbots/$id/edit'
    | '/admin/products/gadgetbots/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/login'
    | '/admin'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/products'
    | '/admin/products/gadgetbots/new'
    | '/admin/products/gadgetbots/$id/edit'
    | '/admin/products/gadgetbots/$id'
  id:
    | '__root__'
    | '/'
    | '/401'
    | '/403'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/products/'
    | '/admin/products/gadgetbots/new'
    | '/admin/products/gadgetbots/$id/edit'
    | '/admin/products/gadgetbots/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/gadgetbots/new': {
      id: '/admin/products/gadgetbots/new'
      path: '/products/gadgetbots/new'
      fullPath: '/admin/products/gadgetbots/new'
      preLoaderRoute: typeof AdminProductsGadgetbotsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/gadgetbots/$id/': {
      id: '/admin/products/gadgetbots/$id/'
      path: '/products/gadgetbots/$id'
      fullPath: '/admin/products/gadgetbots/$id'
      preLoaderRoute: typeof AdminProductsGadgetbotsIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/gadgetbots/$id/edit': {
      id: '/admin/products/gadgetbots/$id/edit'
      path: '/products/gadgetbots/$id/edit'
      fullPath: '/admin/products/gadgetbots/$id/edit'
      preLoaderRoute: typeof AdminProductsGadgetbotsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsGadgetbotsNewRoute: typeof AdminProductsGadgetbotsNewRoute
  AdminProductsGadgetbotsIdEditRoute: typeof AdminProductsGadgetbotsIdEditRoute
  AdminProductsGadgetbotsIdIndexRoute: typeof AdminProductsGadgetbotsIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsGadgetbotsNewRoute: AdminProductsGadgetbotsNewRoute,
  AdminProductsGadgetbotsIdEditRoute: AdminProductsGadgetbotsIdEditRoute,
  AdminProductsGadgetbotsIdIndexRoute: AdminProductsGadgetbotsIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
